### ISSUE TITLE
Crash when starting the app

### ISSUE THREAD

**Issue by caishuyao** [caishuyao/SDM2020_Team5_SEER#17]
Although the deployment finished without error, abut the server start and turn into crash state.

**Comment by caishuyao** [comment]
I suggest that It may fix by using an independent server.js.

**Comment by CHENJ137** [comment]
Maybe modify the scripts in package.json file.

**Comment by sregula91** [comment]
Can we use a Procfile to reduce this issue

**Comment by caishuyao** [comment]
I find out that it should configure on heroku using a create-react-app-buildpack to fix this problem.
we now can use react-scripts start in both local and heroku environment.

**Comment by caishuyao** [comment]
After fully testing, this issue has been solved.
