### ISSUE TITLE
Deploy on Heroku unsuccessful.

### ISSUE THREAD

**Issue by CHENJ137** [caishuyao/SDM2020_Team5_SEER#27]
![image](https://user-images.githubusercontent.com/30676770/96266183-d8f80f00-1022-11eb-9576-6ed35c6100bd.png)
Please see attached screenshot.

**Comment by caishuyao** [comment]
Because of combination of backend and frontend, the server did not find the correct path for frontend

fixed the path. now you can see them on heroku
